### ISSUE TITLE
How to pass a custom name/location of an env file?

### ISSUE THREAD

**Issue by jerrygreen** [formatlos/dotenv-load#3]
I don't see this in docs.

Look at this documentation of `dotenv`: https://github.com/motdotla/dotenv#path

I've tried the same option - it doesn't work :( Isn't this supported?

**Comment by jerrygreen** [comment]
I've read the code, found it's already working. In a bit weird way, however.

But it's ok for me, so I've just added some info to the `README.md`: https://github.com/formatlos/dotenv-load/pull/4

**Comment by formatlos** [comment]
@JerryGreen I've added that as a quick hack at some point, therefore I didn't think about it in detail. That's the reason for being quite weird and not documented.
